export interface VocabItem {
  id: string;
  ru: string;
}

export const vocabularyData: Record<string, VocabItem[]> = {
  clothing: [
    { id: 'shirt', ru: 'Рубашка' },
    { id: 'tshirt', ru: 'Футболка' },
    { id: 'pants', ru: 'Брюки' },
    { id: 'jeans', ru: 'Джинсы' },
    { id: 'dress', ru: 'Платье' },
    { id: 'skirt', ru: 'Юбка' },
    { id: 'sweater', ru: 'Свитер' },
    { id: 'jacket', ru: 'Куртка' },
    { id: 'coat', ru: 'Пальто' },
    { id: 'shoes', ru: 'Обувь' },
    { id: 'boots', ru: 'Ботинки' },
    { id: 'sneakers', ru: 'Кроссовки' },
    { id: 'hat', ru: 'Шапка' },
    { id: 'scarf', ru: 'Шарф' },
    { id: 'gloves', ru: 'Перчатки' },
    { id: 'socks', ru: 'Носки' }
  ],
  health: [
    { id: 'doctor', ru: 'Врач' },
    { id: 'hospital', ru: 'Больница' },
    { id: 'pharmacy', ru: 'Аптека' },
    { id: 'medicine', ru: 'Лекарство' },
    { id: 'pain', ru: 'Боль' },
    { id: 'temperature', ru: 'Температура' },
    { id: 'fever', ru: 'Жар' },
    { id: 'cold', ru: 'Простуда' },
    { id: 'cough', ru: 'Кашель' },
    { id: 'headache', ru: 'Головная боль' },
    { id: 'ambulance', ru: 'Скорая помощь' },
    { id: 'help_me', ru: 'Помогите мне' },
    { id: 'i_feel_bad', ru: 'Я плохо себя чувствую' }
  ],
  travel: [
    { id: 'ticket', ru: 'Билет' },
    { id: 'passport', ru: 'Паспорт' },
    { id: 'luggage', ru: 'Багаж' },
    { id: 'suitcase', ru: 'Чемодан' },
    { id: 'train', ru: 'Поезд' },
    { id: 'plane', ru: 'Самолёт' },
    { id: 'station', ru: 'Вокзал' },
    { id: 'airport', ru: 'Аэропорт' },
    { id: 'platform', ru: 'Платформа' },
    { id: 'gate', ru: 'Выход на посадку' },
    { id: 'departure', ru: 'Отправление' },
    { id: 'arrival', ru: 'Прибытие' },
    { id: 'customs', ru: 'Таможня' },
    { id: 'visa', ru: 'Виза' },
    { id: 'seat', ru: 'Место' }
  ],
  education: [
    { id: 'school', ru: 'Школа' },
    { id: 'university', ru: 'Университет' },
    { id: 'student', ru: 'Студент' },
    { id: 'teacher', ru: 'Учитель' },
    { id: 'professor', ru: 'Преподаватель' },
    { id: 'book', ru: 'Книга' },
    { id: 'textbook', ru: 'Учебник' },
    { id: 'notebook', ru: 'Тетрадь' },
    { id: 'pen', ru: 'Ручка' },
    { id: 'exam', ru: 'Экзамен' },
    { id: 'lesson', ru: 'Урок' },
    { id: 'homework', ru: 'Домашнее задание' },
    { id: 'grade', ru: 'Оценка' },
    { id: 'library', ru: 'Библиотека' }
  ],
  body: [
    { id: 'body', ru: 'Тело' },
    { id: 'head', ru: 'Голова' },
    { id: 'face', ru: 'Лицо' },
    { id: 'eye', ru: 'Глаз' },
    { id: 'eyes', ru: 'Глаза' },
    { id: 'nose', ru: 'Нос' },
    { id: 'mouth', ru: 'Рот' },
    { id: 'ear', ru: 'Ухо' },
    { id: 'ears', ru: 'Уши' },
    { id: 'hair', ru: 'Волосы' },
    { id: 'arm_hand', ru: 'Рука' },
    { id: 'leg_foot', ru: 'Нога' },
    { id: 'finger', ru: 'Палец' },
    { id: 'stomach', ru: 'Живот' },
    { id: 'heart', ru: 'Сердце' },
    { id: 'back', ru: 'Спина' }
  ],
  nature: [
    { id: 'nature', ru: 'Природа' },
    { id: 'sun', ru: 'Солнце' },
    { id: 'moon', ru: 'Луна' },
    { id: 'sky', ru: 'Небо' },
    { id: 'star', ru: 'Звезда' },
    { id: 'cloud', ru: 'Облако' },
    { id: 'rain', ru: 'Дождь' },
    { id: 'snow', ru: 'Снег' },
    { id: 'wind', ru: 'Ветер' },
    { id: 'tree', ru: 'Дерево' },
    { id: 'flower', ru: 'Цветок' },
    { id: 'forest', ru: 'Лес' },
    { id: 'river', ru: 'Река' },
    { id: 'sea', ru: 'Море' },
    { id: 'mountain', ru: 'Гора' }
  ],
  celebrations: [
    { id: 'holiday', ru: 'Праздник' },
    { id: 'birthday', ru: 'День рождения' },
    { id: 'new_year', ru: 'Новый год' },
    { id: 'christmas', ru: 'Рождество' },
    { id: 'easter', ru: 'Пасха' },
    { id: 'gift', ru: 'Подарок' },
    { id: 'party', ru: 'Вечеринка' },
    { id: 'guest', ru: 'Гость' },
    { id: 'cake', ru: 'Торт' },
    { id: 'flowers', ru: 'Цветы' },
    { id: 'card', ru: 'Открытка' },
    { id: 'congratulations', ru: 'Поздравляю' },
    { id: 'cheers', ru: 'За здоровье' }
  ]
};
